version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: baullin/vpn_bot:latest
    command: python app.py
    restart: always
    env_file:
      - ".env"
    volumes:
      - ../..:/workspaces:cached

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
